language: node_js
node_js:
  - '8.10.0'

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install netlify-cli -g

install:
  - yarn install --pure-lockfile

script:
  - yarn lint:styles
  - yarn lint:js

env:
  - BASE_URL=https://vibrant-edison-a476b8.netlify.com

before_deploy:
  - yarn build

deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  skip_cleanup: true
